config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :books, only: %i[index show] do
    resources :comments, only: :create
  end

  namespace :users do
    resource :address, only: %i[update]
  end

  resources :categories do
    resources :books, only: :index
  end

  resources :order_items, only: %i[update create destroy]

  resource :cart, only: :show do
    get :checkout
  end

  resources :orders, only: %i[show index]

  resource :coupon, only: [] do
    patch :apply
  end

  namespace :checkout do
    resource :fill_address, only: %i[show create]
    resource :fill_delivery, only: %i[show create]
    resource :fill_payment, only: %i[show create]
    resource :fill_confirm, only: %i[show create]
    get '/fill_complete/:number', as: 'fill_complete', to: 'fill_completes#show'
  end

  root 'home#index'
end

app/controllers/checkout/fill_addresses_controller.rb
module Checkout
  class FillAddressesController < ApplicationController
    include CheckoutConcern

    def show
      redirect_to(cart_path) && return unless check_step(:fill_address)
      Checkout::FillAddress::BuildAddresses.call(order: current_order, user: current_user)
    end

    def create
      Checkout::FillAddress::Organizer.call(
        order: current_order,
        params: address_params,
        hidden_shipping_form: params[:hidden_shipping_form],
        allowed_status: :fill_address
      )
      redirect_to checkout_step_path
    end

    private

    def address_params
      params.require(:order).permit(
        shipping_address_attributes: Address::ADDRESS_PARAMS,
        billing_address_attributes: Address::ADDRESS_PARAMS
      )
    end
  end
end

app/controllers/checkout/fill_completes_controller.rb
module Checkout
  class FillCompletesController < ApplicationController
    include CheckoutConcern

    def show
      @order = current_user.orders.find_by!(number: params[:number]).decorate
      @order_items = @order.order_items.decorate
    end
  end
end

app/controllers/checkout/fill_confirms_controller.rb
module Checkout
  class FillConfirmsController < ApplicationController
    include CheckoutConcern

    def show
      redirect_to(checkout_step_path) && return unless check_step(:fill_confirm)
    end

    def create
      result = Checkout::FillConfirm::Organizer.call(order: current_order, allowed_status: :fill_confirm)
      redirect_to(checkout_step_path) && return unless result.success?
      session[:order_id] = nil

      redirect_to checkout_fill_complete_path(current_order.number)
    end
  end
end

app/controllers/checkout/fill_deliveries_controller.rb
module Checkout
  class FillDeliveriesController < ApplicationController
    include CheckoutConcern

    def show
      redirect_to(checkout_step_path) && return unless check_step(:fill_delivery)
      @deliveries = Delivery.all.order(price: :asc)
    end

    def create
      Checkout::FillDelivery::Organizer.call(
        order: current_order,
        params: delivery_params,
        allowed_status: :fill_delivery
      )
      redirect_to checkout_step_path
    end

    private

    def delivery_params
      params.require(:order).permit(:delivery_id)
    end
  end
end

app/controllers/checkout/fill_payments_controller.rb
module Checkout
  class FillPaymentsController < ApplicationController
    include CheckoutConcern

    def show
      redirect_to(checkout_step_path) && return unless check_step(:fill_payment)
      @payment = Payment.first_or_initialize(order_id: current_order.id)
    end

    def create
      Checkout::FillPayment::Organizer.call(allowed_status: :fill_payment, order: current_order, params: payment_params)
      redirect_to checkout_step_path
    end

    private

    def payment_params
      params.require(:payment).permit(:number, :name, :cvv, :date)
    end
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  LAST_STEP = 5

  def clickable_steps
    Order::STEPS.first(4)
  end
end

app/views/checkout/fill_payments/show.html.haml
%main.container.mb-res-50
  %h1.general-title-margin
    = t('checkout.title')
  %ul.steps.list-inline
    = render 'checkout/partials/checkout_steps'
  %h3.general-subtitle
    = t('checkout.payment.title')
  = simple_form_for(@payment, url: checkout_fill_payment_path, validate: true, defaults: { input_html: { class: "form-control"}}, html: { method: :post }) do |f|
    .max-600.mb-80
      = f.input :number, placeholder: t('checkout.payment.placeholder.cart_number')
      .row.mt-30
        .col-sm-6
          = f.input :name, placeholder: t('checkout.payment.placeholder.name_on_card'), input_html: { value: @payment.name }
        .col-sm-3
          = f.input :date,  placeholder: t('checkout.payment.placeholder.date')
        .col-sm-3
          = f.input :cvv,  placeholder: t('checkout.payment.placeholder.cvv')
          .hint_cvv
            %i.fa.fa-question-circle.general-form-help
            %span
              = t('checkout.payment.hint')
    .general-text-left
      = render 'checkout/partials/order_summary', order: current_order
    .text-center
      = f.submit t('btn.save_and_continue'), class: "btn btn-default mb-80"