config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :books, only: %i[index show] do
    resources :comments, only: :create
  end

  namespace :users do
    resource :address, only: %i[update]
  end

  resources :categories do
    resources :books, only: :index
  end

  resources :order_items, only: %i[update create destroy]

  resource :cart, only: :show do
    get :checkout
  end

  resources :orders, only: %i[show index]

  resource :coupon, only: [] do
    patch :apply
  end

  namespace :checkout do
    resource :fill_address, only: %i[show create]
    resource :fill_delivery, only: %i[show create]
    resource :fill_payment, only: %i[show create]
    resource :fill_confirm, only: %i[show create]
    get '/fill_complete/:number', as: 'fill_complete', to: 'fill_completes#show'
  end

  root 'home#index'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :book
  belongs_to :order

  delegate :price, to: :book, prefix: true

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :setup_order_item, except: [:create]

  def create
    result = OrderItems::Create.call(params: permitted_params, current_order: current_order)
    if result.success?
      redirect_back(fallback_location: root_path, notice: t('order_item.success_update'))
    else
      redirect_to cart_path, flash: { danger: t('order_item.error_update') }
    end
    session[:order_id] ||= current_order.id
  end

  def destroy
    @order_item.destroy
    redirect_to cart_path, flash: { success: t('order_item.success_delete') }
  end

  def update
    result = OrderItems::Update.call(params: params, order_item: @order_item)
    if result.success?
      redirect_to cart_path, flash: { success: t('order_item.success_update') }
    else
      redirect_to cart_path, flash: { danger: t('order_item.error_update') }
    end
  end

  private

  def setup_order_item
    @order_item = OrderItem.find(params[:id])
  end

  def permitted_params
    params.require(:order_items).permit(:quantity, :book_id)
  end
end

app/views/shared/order_items/_order_items.html.haml
%table.table.table-hover
  %thead
    %tr
      %th
        %span.in-grey-600
          = t('order_item.book')
      %th.col-method
      %th
        %span.in-grey-600
          = t('order_item.price')
      %th
        %span.in-grey-600
          = t('order_item.quantity')
      %th
        %span.in-grey-600
          = t('order_item.total')
  - order_items.each do |order_item|
    %tbody
      %tr
        %td
          .general-img-wrap-table
            = link_to book_path(order_item.book.id) do
              = image_tag(order_item.book.first_book_image(:medium_img), class: "cart-img-shadow pull-left", alt: "design-book")
        %td
          %p.title
            = order_item.book.name
          %p.in-grey-600.fw-300
            = order_item.book.description
        %td
          %span.font-16.in-gold-500
            = number_to_currency(order_item.book.price)
        %td
          %span.ml-30
            = order_item.quantity
        %td
          %span.font-16.in-gold-500
            = number_to_currency(order_item.price)