config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :books, only: %i[index show] do
    resources :comments, only: :create
  end

  namespace :users do
    resource :address, only: %i[update]
  end

  resources :categories do
    resources :books, only: :index
  end

  resources :order_items, only: %i[update create destroy]

  resource :cart, only: :show do
    get :checkout
  end

  resources :orders, only: %i[show index]

  resource :coupon, only: [] do
    patch :apply
  end

  namespace :checkout do
    resource :fill_address, only: %i[show create]
    resource :fill_delivery, only: %i[show create]
    resource :fill_payment, only: %i[show create]
    resource :fill_confirm, only: %i[show create]
    get '/fill_complete/:number', as: 'fill_complete', to: 'fill_completes#show'
  end

  root 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
  ADDRESS_PARAMS = %i[first_name last_name address city zip country phone].freeze

  belongs_to :addressable, polymorphic: true

  validates :first_name, presence: true, length: { in: 2..50 }
  validates :last_name, presence: true, length: { in: 2..50 }
  validates :address, presence: true, length: { in: 2..100 }
  validates :city, presence: true, length: { in: 2..50 }
  validates :zip, presence: true, length: { in: 1..9 }, format: { with: /\A[0-9]+\z/ }
  validates :country, presence: true, length: { in: 2..50 }
  validates :phone, presence: true, length: { in: 10..15 }, format: { with: /\A[+][0-9]+\z/ }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/billing_address.rb
class BillingAddress < Address
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :book_materials, dependent: :destroy
  has_many :materials, through: :book_materials
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors
  has_many :book_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :order_items, dependent: :nullify

  accepts_nested_attributes_for :book_images, allow_destroy: true

  validates :name, presence: true, length: { in: 0..50 }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal: 0, less_than_or_equal: 10_000 }
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  belongs_to :book

  mount_uploader :image, ImageUploader
end

app/models/book_material.rb
class BookMaterial < ApplicationRecord
  belongs_to :book
  belongs_to :material
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  COUNT_STARTS = 5

  belongs_to :user
  belongs_to :book

  delegate :email, to: :user, prefix: true

  validates :title, :mark, :description, presence: true
  validates :title, length: { in: 2..50 }
  validates :description, length: { in: 10..500 }
  validates :mark, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :orders, dependent: :nullify
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :nullify
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :books, through: :book_materials
  has_many :book_materials, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  STEPS = %i[fill_address fill_delivery fill_payment fill_confirm fill_complete].freeze
  FINISH_STATUSES = %i[in_progress in_delivery delivered canceled].freeze

  belongs_to :user, optional: true
  belongs_to :delivery, optional: true
  belongs_to :coupon, optional: true

  has_many :order_items, dependent: :destroy
  has_many :addresses, as: :addressable, dependent: :destroy

  has_one :billing_address, as: :addressable, dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy
  has_one :payment, dependent: :destroy

  accepts_nested_attributes_for :shipping_address, :billing_address, update_only: true

  enum status: {
    cart: 0,
    fill_address: 1,
    fill_delivery: 2,
    fill_payment: 3,
    fill_confirm: 4,
    in_progress: 5,
    in_delivery: 6,
    delivered: 7,
    canceled: 8
  }

  aasm :status, enum: true do # rubocop:disable Metrics/BlockLength
    state :cart, initial: true
    state :fill_address
    state :fill_delivery
    state :fill_payment
    state :fill_confirm
    state :fill_complete
    state :in_progress
    state :in_delivery
    state :delivered
    state :canceled

    event :filling_address do
      transitions from: :cart, to: :fill_address
    end

    event :filling_delivering do
      transitions from: :fill_address, to: :fill_delivery
    end

    event :filling_payments do
      transitions from: :fill_delivery, to: :fill_payment
    end

    event :filling_confirm do
      transitions from: :fill_payment, to: :fill_confirm
    end

    event :confirm do
      transitions from: :fill_confirm, to: :in_progress
    end

    event :deliver do
      transitions from: :in_progress, to: :in_delivery
    end

    event :confirm_delivery do
      transitions from: :in_delivery, to: :delivered
    end

    event :cancel do
      transitions from: %i[in_progress in_delivery delivered], to: :canceled
    end
  end

  after_update do |order|
    if order.delivered? && order.status_previously_changed?
      order.order_items.each do |item|
        item.book.increment!(:buy_count) # rubocop:disable Rails/SkipsModelValidations
      end
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :book
  belongs_to :order

  delegate :price, to: :book, prefix: true

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order, dependent: :destroy

  validates :number, presence: true, length: { is: 16 }, format: { with: /\A[0-9]+\z/ }
  validates :cvv, presence: true, length: { in: 3..4 }, format: { with: /\A[0-9]+\z/ }
  validates :name, presence: true, length: { in: 1..50 }
  validates :date, presence: true, length: { in: 4..5 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :confirmable,
         :registerable, :recoverable, :rememberable,
         :validatable, :omniauthable, omniauth_providers: %i[facebook]

  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy

  has_one :billing_address, as: :addressable, dependent: :destroy
  has_one :shipping_address, as: :addressable, dependent: :destroy

  accepts_nested_attributes_for :shipping_address, :billing_address, update_only: true
end

app/helpers/books_helper.rb
module BooksHelper
  include Pagy::Frontend
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  LAST_STEP = 5

  def clickable_steps
    Order::STEPS.first(4)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def radio_btn_option
    Array.new(Comment::COUNT_STARTS) { |i| [i.next] }
  end
end

app/views/layouts/partials/_cart.html.haml
- unless current_order.nil?
  - if current_order.persisted? && !current_order.order_items.empty?
    = link_to cart_path, {class: 'shop-link pull-right hidden-xs'} do
      %span.shop-icon
        %span.shop-quantity
          = current_order.items_sum
  - if current_order.persisted? && !current_order.order_items.empty?
    = link_to cart_path, {class: 'shop-link pull-right visible-xs'} do
      %span.shop-icon
        %span.shop-quantity
          = current_order.items_sum

app/views/layouts/partials/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to t('btn.home'), root_path, class: 'nav-link'
          %li
            = link_to t('btn.books'), books_path, class: 'nav-link'
          %li
            %a.nav-link{href: "#"}
              = t('btn.orders')
          %li
            %a.nav-link{href: "#"}
              = t('btn.settings')
      .col-sm-3
        %p.general-nav-mail
          = t('contacts.email')
        %p.general-nav-number
          = t('contacts.number')
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/layouts/partials/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand
        = t('.bookstore')
        = render partial: 'layouts/partials/cart'
      #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
        - if user_signed_in?
          %ul.nav.navbar-nav
            %li.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
                = t('btn.account')
              %ul.dropdown-menu
                %li
                  = link_to t('sign.orders'), orders_path, class: "collapse-link"
                %li
                  = link_to t('sign.settings'), edit_user_registration_path, class: "collapse-link"
                %li.divider{role: "separator"}
                %li
                  = link_to t('btn.out'), destroy_user_session_path, method: :delete, class: "collapse-link"
        - else
          %ul.nav.navbar-nav
            %li.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
                = t('btn.account')
              %ul.dropdown-menu
                %li
                  = link_to t('devise.login'), new_user_session_path, class: "collapse-link"
                %li
                  = link_to t('devise.sign_up'), new_user_registration_path, class: "collapse-link"

        %ul.nav.navbar-nav
          %li
            = link_to t('header.home'), root_path
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
              = t('header.shop')
            %ul.dropdown-menu
              %li
                = link_to t('header.all_books'), books_path
              - categories.each do |category|
                %li
                  = link_to books_path(category: category), class: 'filter-link' do
                    = category.name